site_name: DevOps Guide Bruno Staub

nav:
  - Startseite: index.md
  - DevOPS:
    - DevOps Bible: devops_bible.md
    - Docker: docker.md
    - Ansible: ansible.md
    - Kubernetes: k8s.md
    - Terraform: tf.md
    - Linux: linux.md
  - Aufgaben:
    - Lehrlingsaufgaben für den ESXi-Cluster: vmware_aufgaben.md
    - Arbeitsanweisung Aufbau Nested Cluster: vmware_nested_cluster.md
    - Arbeitsanweisung Physical 3-Node Cluster Setup: vmware_physical_cluster.md
  - Ressourcen:
    - Link Liste: vmware_linklist.md
    - Videos: vmware_videos.md
  - Other:
    - Mkdocs: mkdocs.md
    - Git: git.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: de
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bstaub/mkdocs-bstaub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bruno-staub/
    #- icon: fontawesome/brands/twitter
    #  link: https://twitter.com/TheJamesWillett      

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2024 <a href="https://github.com/bstaub/mkdocs-bstaub"  target="_blank" rel="noopener">github.com/bstaub/mkdocs-bstaub</a>